from enum import Enum


class PaymentStatus(str, Enum):
    """Основные статусы платежа"""

    NEW = "NEW"
    FORM_SHOWED = "FORM_SHOWED"
    AUTHORIZING = "AUTHORIZING"
    THREE_DS_CHECKING = "3DS_CHECKING"
    THREE_DS_CHECKED = "3DS_CHECKED"
    AUTHORIZED = "AUTHORIZED"
    CONFIRMING = "CONFIRMING"
    CONFIRMED = "CONFIRMED"
    REVERSING = "REVERSING"
    PARTIAL_REVERSED = "PARTIAL_REVERSED"
    REVERSED = "REVERSED"
    REFUNDING = "REFUNDING"
    PARTIAL_REFUNDED = "PARTIAL_REFUNDED"
    REFUNDED = "REFUNDED"
    CANCELED = "CANCELED"
    DEADLINE_EXPIRED = "DEADLINE_EXPIRED"
    REJECTED = "REJECTED"
    AUTH_FAIL = "AUTH_FAIL"
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
